// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bus/v1/execution_request.proto

package busv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderSide enumerates the desired trade side semantics.
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
	OrderSide_ORDER_SIDE_OPEN        OrderSide = 3
	OrderSide_ORDER_SIDE_CLOSE       OrderSide = 4
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
		3: "ORDER_SIDE_OPEN",
		4: "ORDER_SIDE_CLOSE",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
		"ORDER_SIDE_OPEN":        3,
		"ORDER_SIDE_CLOSE":       4,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_v1_execution_request_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_bus_v1_execution_request_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_bus_v1_execution_request_proto_rawDescGZIP(), []int{0}
}

// OrderType captures the desired order style at the venue.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_MARKET      OrderType = 1
	OrderType_ORDER_TYPE_LIMIT       OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_v1_execution_request_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_bus_v1_execution_request_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_bus_v1_execution_request_proto_rawDescGZIP(), []int{1}
}

// TimeInForce represents the lifetime policy for the order at the venue.
type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_v1_execution_request_proto_enumTypes[2].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_bus_v1_execution_request_proto_enumTypes[2]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_bus_v1_execution_request_proto_rawDescGZIP(), []int{2}
}

// ExecutionRequestSource identifies the upstream producer of the execution request.
type ExecutionRequestSource int32

const (
	ExecutionRequestSource_EXECUTION_REQUEST_SOURCE_UNSPECIFIED ExecutionRequestSource = 0
	ExecutionRequestSource_EXECUTION_REQUEST_SOURCE_MATCHER_V1  ExecutionRequestSource = 1
)

// Enum value maps for ExecutionRequestSource.
var (
	ExecutionRequestSource_name = map[int32]string{
		0: "EXECUTION_REQUEST_SOURCE_UNSPECIFIED",
		1: "EXECUTION_REQUEST_SOURCE_MATCHER_V1",
	}
	ExecutionRequestSource_value = map[string]int32{
		"EXECUTION_REQUEST_SOURCE_UNSPECIFIED": 0,
		"EXECUTION_REQUEST_SOURCE_MATCHER_V1":  1,
	}
)

func (x ExecutionRequestSource) Enum() *ExecutionRequestSource {
	p := new(ExecutionRequestSource)
	*p = x
	return p
}

func (x ExecutionRequestSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionRequestSource) Descriptor() protoreflect.EnumDescriptor {
	return file_bus_v1_execution_request_proto_enumTypes[3].Descriptor()
}

func (ExecutionRequestSource) Type() protoreflect.EnumType {
	return &file_bus_v1_execution_request_proto_enumTypes[3]
}

func (x ExecutionRequestSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionRequestSource.Descriptor instead.
func (ExecutionRequestSource) EnumDescriptor() ([]byte, []int) {
	return file_bus_v1_execution_request_proto_rawDescGZIP(), []int{3}
}

// ExecutionRequest encapsulates a normalized execution intent emitted by the matcher.
type ExecutionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionRequestId string                 `protobuf:"bytes,1,opt,name=execution_request_id,json=executionRequestId,proto3" json:"execution_request_id,omitempty"`
	SignalId           string                 `protobuf:"bytes,2,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	InfluencerId       string                 `protobuf:"bytes,3,opt,name=influencer_id,json=influencerId,proto3" json:"influencer_id,omitempty"`
	SubscriberId       string                 `protobuf:"bytes,4,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	SubscriptionId     string                 `protobuf:"bytes,5,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	Market             string                 `protobuf:"bytes,6,opt,name=market,proto3" json:"market,omitempty"`
	Side               OrderSide              `protobuf:"varint,7,opt,name=side,proto3,enum=bus.v1.OrderSide" json:"side,omitempty"`
	OrderType          OrderType              `protobuf:"varint,8,opt,name=order_type,json=orderType,proto3,enum=bus.v1.OrderType" json:"order_type,omitempty"`
	Quantity           float64                `protobuf:"fixed64,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Notional           float64                `protobuf:"fixed64,10,opt,name=notional,proto3" json:"notional,omitempty"`
	Price              float64                `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`
	Leverage           float64                `protobuf:"fixed64,12,opt,name=leverage,proto3" json:"leverage,omitempty"`
	TimeInForce        TimeInForce            `protobuf:"varint,13,opt,name=time_in_force,json=timeInForce,proto3,enum=bus.v1.TimeInForce" json:"time_in_force,omitempty"`
	RiskChecksPassed   bool                   `protobuf:"varint,14,opt,name=risk_checks_passed,json=riskChecksPassed,proto3" json:"risk_checks_passed,omitempty"`
	RejectionReason    string                 `protobuf:"bytes,15,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	Source             ExecutionRequestSource `protobuf:"varint,16,opt,name=source,proto3,enum=bus.v1.ExecutionRequestSource" json:"source,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	TraceId            string                 `protobuf:"bytes,18,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CorrelationId      string                 `protobuf:"bytes,19,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_bus_v1_execution_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bus_v1_execution_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_bus_v1_execution_request_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetExecutionRequestId() string {
	if x != nil {
		return x.ExecutionRequestId
	}
	return ""
}

func (x *ExecutionRequest) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *ExecutionRequest) GetInfluencerId() string {
	if x != nil {
		return x.InfluencerId
	}
	return ""
}

func (x *ExecutionRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *ExecutionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *ExecutionRequest) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *ExecutionRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *ExecutionRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *ExecutionRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ExecutionRequest) GetNotional() float64 {
	if x != nil {
		return x.Notional
	}
	return 0
}

func (x *ExecutionRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ExecutionRequest) GetLeverage() float64 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *ExecutionRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *ExecutionRequest) GetRiskChecksPassed() bool {
	if x != nil {
		return x.RiskChecksPassed
	}
	return false
}

func (x *ExecutionRequest) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *ExecutionRequest) GetSource() ExecutionRequestSource {
	if x != nil {
		return x.Source
	}
	return ExecutionRequestSource_EXECUTION_REQUEST_SOURCE_UNSPECIFIED
}

func (x *ExecutionRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExecutionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecutionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

var File_bus_v1_execution_request_proto protoreflect.FileDescriptor

const file_bus_v1_execution_request_proto_rawDesc = "" +
	"\n" +
	"\x1ebus/v1/execution_request.proto\x12\x06bus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x05\n" +
	"\x10ExecutionRequest\x120\n" +
	"\x14execution_request_id\x18\x01 \x01(\tR\x12executionRequestId\x12\x1b\n" +
	"\tsignal_id\x18\x02 \x01(\tR\bsignalId\x12#\n" +
	"\rinfluencer_id\x18\x03 \x01(\tR\finfluencerId\x12#\n" +
	"\rsubscriber_id\x18\x04 \x01(\tR\fsubscriberId\x12'\n" +
	"\x0fsubscription_id\x18\x05 \x01(\tR\x0esubscriptionId\x12\x16\n" +
	"\x06market\x18\x06 \x01(\tR\x06market\x12%\n" +
	"\x04side\x18\a \x01(\x0e2\x11.bus.v1.OrderSideR\x04side\x120\n" +
	"\n" +
	"order_type\x18\b \x01(\x0e2\x11.bus.v1.OrderTypeR\torderType\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x01R\bquantity\x12\x1a\n" +
	"\bnotional\x18\n" +
	" \x01(\x01R\bnotional\x12\x14\n" +
	"\x05price\x18\v \x01(\x01R\x05price\x12\x1a\n" +
	"\bleverage\x18\f \x01(\x01R\bleverage\x127\n" +
	"\rtime_in_force\x18\r \x01(\x0e2\x13.bus.v1.TimeInForceR\vtimeInForce\x12,\n" +
	"\x12risk_checks_passed\x18\x0e \x01(\bR\x10riskChecksPassed\x12)\n" +
	"\x10rejection_reason\x18\x0f \x01(\tR\x0frejectionReason\x126\n" +
	"\x06source\x18\x10 \x01(\x0e2\x1e.bus.v1.ExecutionRequestSourceR\x06source\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\btrace_id\x18\x12 \x01(\tR\atraceId\x12%\n" +
	"\x0ecorrelation_id\x18\x13 \x01(\tR\rcorrelationId*{\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02\x12\x13\n" +
	"\x0fORDER_SIDE_OPEN\x10\x03\x12\x14\n" +
	"\x10ORDER_SIDE_CLOSE\x10\x04*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02*q\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x03*k\n" +
	"\x16ExecutionRequestSource\x12(\n" +
	"$EXECUTION_REQUEST_SOURCE_UNSPECIFIED\x10\x00\x12'\n" +
	"#EXECUTION_REQUEST_SOURCE_MATCHER_V1\x10\x01BEZCgithub.com/0xRichardL/vibe-copy-trading/libs/go/domain/bus/v1;busv1b\x06proto3"

var (
	file_bus_v1_execution_request_proto_rawDescOnce sync.Once
	file_bus_v1_execution_request_proto_rawDescData []byte
)

func file_bus_v1_execution_request_proto_rawDescGZIP() []byte {
	file_bus_v1_execution_request_proto_rawDescOnce.Do(func() {
		file_bus_v1_execution_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bus_v1_execution_request_proto_rawDesc), len(file_bus_v1_execution_request_proto_rawDesc)))
	})
	return file_bus_v1_execution_request_proto_rawDescData
}

var file_bus_v1_execution_request_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_bus_v1_execution_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bus_v1_execution_request_proto_goTypes = []any{
	(OrderSide)(0),                // 0: bus.v1.OrderSide
	(OrderType)(0),                // 1: bus.v1.OrderType
	(TimeInForce)(0),              // 2: bus.v1.TimeInForce
	(ExecutionRequestSource)(0),   // 3: bus.v1.ExecutionRequestSource
	(*ExecutionRequest)(nil),      // 4: bus.v1.ExecutionRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_bus_v1_execution_request_proto_depIdxs = []int32{
	0, // 0: bus.v1.ExecutionRequest.side:type_name -> bus.v1.OrderSide
	1, // 1: bus.v1.ExecutionRequest.order_type:type_name -> bus.v1.OrderType
	2, // 2: bus.v1.ExecutionRequest.time_in_force:type_name -> bus.v1.TimeInForce
	3, // 3: bus.v1.ExecutionRequest.source:type_name -> bus.v1.ExecutionRequestSource
	5, // 4: bus.v1.ExecutionRequest.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bus_v1_execution_request_proto_init() }
func file_bus_v1_execution_request_proto_init() {
	if File_bus_v1_execution_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bus_v1_execution_request_proto_rawDesc), len(file_bus_v1_execution_request_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bus_v1_execution_request_proto_goTypes,
		DependencyIndexes: file_bus_v1_execution_request_proto_depIdxs,
		EnumInfos:         file_bus_v1_execution_request_proto_enumTypes,
		MessageInfos:      file_bus_v1_execution_request_proto_msgTypes,
	}.Build()
	File_bus_v1_execution_request_proto = out.File
	file_bus_v1_execution_request_proto_goTypes = nil
	file_bus_v1_execution_request_proto_depIdxs = nil
}
